backend:
  name: turbo-github
  turbo_site_id: 58de630d-e7eb-40ae-af48-4589a6b001d8
  branch: main

media_folder: "static/images/uploads"
public_folder: "/images/uploads"

collections:
  - name: "posts"
    label: "文章"
    folder: "content/posts"
    create: true
    slug: "{{year}}-{{month}}-{{day}}-{{slug}}"

    fields:
      - label: "标题"
        name: "title"
        widget: "string"

      - label: "日期"
        name: "date"
        widget: "datetime"

      - label: "草稿"
        name: "draft"
        widget: "boolean"
        default: false

      - label: "正文"
        name: "body"
        widget: "markdown"